version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"          
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - product-service
      - order-service

  auth-service:
    build: ./auth
    container_name: auth-service
    # ❌ Không expose ra ngoài để Postman không truy cập trực tiếp được
    expose:
      - "3000"
    env_file:
      - ./auth/.env
    depends_on:
      - mongo-service

  product-service:
    build: ./product
    container_name: product-service
    expose:
      - "3001"
    env_file:
      - ./product/.env
    depends_on:
      - mongo-service
      - rabbitmq

  order-service:
    build: ./order
    container_name: order-service
    expose:
      - "3002"
    env_file:
      - ./order/.env
    depends_on:
      - mongo-service
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # để các service trong container dùng
      - "15672:15672"    # để bạn mở giao diện quản lý RabbitMQ trên trình duyệt

  mongo-service:
    image: mongo:6
    container_name: mongo-service
    ports:
      - "27017:27017"   
